FROM python:3.13-slim

WORKDIR /app

COPY ../pyproject.toml uv.lock ./
RUN pip install --upgrade pip
RUN pip install uv
RUN uv pip install --system --no-cache -r pyproject.toml --group test

COPY backend .

CMD ["pytest", "--cov=app", "--cov-report=term-missing"]
